### ISSUE TITLE
Number Lock Mecanism

### ISSUE THREAD

**Issue by LirycMoaners** [LirycMoaners/city-key#4]
Add the lock mecanism component in game module, in the mecanism list folder.
This component is a lock where you need to input 4 numbers to unlock it (it takes in entry the good combination to unlock it).
To call this component we will use the angular component factory.
The output will be the success of the mecanism.

**Comment by FeliciaMarlove** [comment]
(fmi) https://stackoverflow.com/questions/49531499/how-to-open-md-dialog-full-screen-angular4
